### ISSUE TITLE
Include an external ID in the IAM role to avoid the confused deputy problem

### ISSUE THREAD

**Issue by marcel-puchol-jt** [VerticeOne/terraform-aws-vertice-integration#14]
Hello,
as commented in https://docs.aws.amazon.com/IAM/latest/UserGuide/confused-deputy.html by AWS, we need to include an External ID in order to avoid the confused deputy problem.

Please, can you add it?

Thanks!

**Comment by gerricchaplin** [comment]
Hello Marcel,

Thank you for raising this issue.
We are already working on an implementation of this to support this requirement.

Unfortunately our next scheduled release is in January due to change freeze and we will not be able to provide this until then.

I will update you with any changes and further information when we have it.

Best regards,
Gerric Chaplin
